export const SDQ_SURAH_ORDER = [
  // JUZ 30 (TERBALIK)
  { surah: "An-Nas", juz: 30, order: 1 },
  { surah: "Al-Falaq", juz: 30, order: 2 },
  { surah: "Al-Ikhlas", juz: 30, order: 3 },
  { surah: "Al-Lahab", juz: 30, order: 4 },
  { surah: "An-Nasr", juz: 30, order: 5 },
  { surah: "Al-Kafirun", juz: 30, order: 6 },
  { surah: "Al-Kautsar", juz: 30, order: 7 },
  { surah: "Al-Ma'un", juz: 30, order: 8 },
  { surah: "Quraisy", juz: 30, order: 9 },
  { surah: "Al-Fil", juz: 30, order: 10 },
  { surah: "Al-Humazah", juz: 30, order: 11 },
  { surah: "Al-'Asr", juz: 30, order: 12 },
  { surah: "At-Takatsur", juz: 30, order: 13 },
  { surah: "Al-Qari'ah", juz: 30, order: 14 },
  { surah: "Al-'Adiyat", juz: 30, order: 15 },
  { surah: "Az-Zalzalah", juz: 30, order: 16 },
  { surah: "Al-Bayyinah", juz: 30, order: 17 },
  { surah: "Al-Qadr", juz: 30, order: 18 },
  { surah: "Al-'Alaq", juz: 30, order: 19 },
  { surah: "At-Tin", juz: 30, order: 20 },
  { surah: "Al-Insyirah", juz: 30, order: 21 },
  { surah: "Ad-Duha", juz: 30, order: 22 },
  { surah: "Al-Lail", juz: 30, order: 23 },
  { surah: "Asy-Syams", juz: 30, order: 24 },
  { surah: "Al-Balad", juz: 30, order: 25 },
  { surah: "Al-Fajr", juz: 30, order: 26 },
  { surah: "Al-Ghasyiyah", juz: 30, order: 27 },
  { surah: "Al-A'la", juz: 30, order: 28 },
  { surah: "Ath-Thariq", juz: 30, order: 29 },
  { surah: "Al-Buruj", juz: 30, order: 30 },
  { surah: "Al-Insyiqaq", juz: 30, order: 31 },
  { surah: "Al-Muthaffifin", juz: 30, order: 32 },
  { surah: "Al-Infitar", juz: 30, order: 33 },
  { surah: "At-Takwir", juz: 30, order: 34 },
  { surah: "'Abasa", juz: 30, order: 35 },
  { surah: "An-Nazi'at", juz: 30, order: 36 },
  { surah: "An-Naba'", juz: 30, order: 37 },

  // JUZ 29
  { surah: "Al-Mulk", juz: 29, order: 38 },
  { surah: "Al-Qalam", juz: 29, order: 39 },
  { surah: "Al-Haqqah", juz: 29, order: 40 },
  { surah: "Al-Ma'arij", juz: 29, order: 41 },
  { surah: "Nuh", juz: 29, order: 42 },
  { surah: "Al-Jinn", juz: 29, order: 43 },
  { surah: "Al-Muzzammil", juz: 29, order: 44 },
  { surah: "Al-Muddassir", juz: 29, order: 45 },
  { surah: "Al-Qiyamah", juz: 29, order: 46 },
  { surah: "Al-Insan", juz: 29, order: 47 },
  { surah: "Al-Mursalat", juz: 29, order: 48 },

  // JUZ 28
  { surah: "Al-Mujadilah", juz: 28, order: 49 },
  { surah: "Al-Hasyr", juz: 28, order: 50 },
  { surah: "Al-Mumtahanah", juz: 28, order: 51 },
  { surah: "As-Saff", juz: 28, order: 52 },
  { surah: "Al-Jumu'ah", juz: 28, order: 53 },
  { surah: "Al-Munafiqun", juz: 28, order: 54 },
  { surah: "At-Taghabun", juz: 28, order: 55 },
  { surah: "At-Talaq", juz: 28, order: 56 },
  { surah: "At-Tahrim", juz: 28, order: 57 },

  // JUZ 27
  { surah: "Adz-Dzariyat", juz: 27, order: 58 },
  { surah: "At-Tur", juz: 27, order: 59 },
  { surah: "An-Najm", juz: 27, order: 60 },
  { surah: "Al-Qamar", juz: 27, order: 61 },
  { surah: "Ar-Rahman", juz: 27, order: 62 },
  { surah: "Al-Waqi'ah", juz: 27, order: 63 },
  { surah: "Al-Hadid", juz: 27, order: 64 },

  // JUZ 26
  { surah: "Al-Ahqaf", juz: 26, order: 65 },
  { surah: "Muhammad", juz: 26, order: 66 },
  { surah: "Al-Fath", juz: 26, order: 67 },
  { surah: "Al-Hujurat", juz: 26, order: 68 },
  { surah: "Qaf", juz: 26, order: 69 },
  { surah: "Adz-Dzariyat", juz: 26, order: 70 },
];
